name: Lint Pull Requests
on:
  pull_request:
    branches: [master, staging/**, develop/**]
    types: [ready_for_review,reopened,review_requested,review_request_removed,opened,edited]
jobs:
  build:
    name: Lint Pull Requests
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'cb-tamizhvendansembiyan' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install '@babel/plugin-transform-flow-strip-types'  
      - name: Run Danger.js Checks
        uses: danger/danger-js@11.0.7
        with:
          args : '--dangerfile .github/distributed-git-flow/pr-linter-danger.js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALTASSIAN_HOST_NAME: mypanda